name: docker_build_and_push
on:
  push:
    branches:
      - main
      - feature/assignment

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short commit hash
        run: echo "::set-output name=short_commit::$(git rev-parse --short ${{ github.sha }})"
        id: commit_hash

      - name: Build Docker image
        run: docker build -t venky3036/kubernetes:${{ steps.commit_hash.outputs.short_commit }} -f project/Dockerfile .
      
      - name: Push Docker image
        run: docker push venky3036/kubernetes:${{ steps.commit_hash.outputs.short_commit }}
