name: build-node-app
on:
  push:
    branches: [ main , feature/assignment ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "12.x"
      - name: Install dependencies
        run: npm install

  upload_to_s3:
    needs: build
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Upload to S3
          uses: jakejarvis/s3-sync-action@v0.4.0
          with:
             args: --acl public-read --follow-symlinks --delete
          env:
                AWS_S3_BUCKET: webhost-demo
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
                SOURCE_DIR: /project/